version: "3.9"
services:
  postgres:
    image: postgres:13.3
    container_name: receipt-db
    user: postgres
    environment:
      POSTGRES_DB: dbase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - web
  receipt-back-end:
    build:
      dockerfile: Dockerfile
      context: ./receipt
    container_name: receipt-back-end
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - web
networks:
  web:
    driver: "bridge"
    name: web