spring:
  application:
    name: receipt
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/dbase
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
calculation:
  service:
    quantity:
      default-quantity: 6
      default-discount: 10
cache:
  type: LFU
  capacity: 3
